import type { PageId as AdminPageId } from "../admin/dashboard/config";
import type { PageId as ClientPageId } from "../client/maphari-dashboard/config";
import type { PageId as StaffPageId } from "../staff/staff-dashboard/config";

export type DashboardNotificationTab = "dashboard" | "projects" | "invoices" | "messages" | "settings" | "operations";

export const CLIENT_PAGE_TO_NOTIFICATION_TAB: Record<ClientPageId, DashboardNotificationTab> = {
  dashboard: "dashboard",
  reports: "dashboard",
  ai: "dashboard",
  onboarding: "dashboard",
  projects: "projects",
  milestones: "projects",
  create: "operations",
  docs: "settings",
  invoices: "invoices",
  messages: "messages",
  automations: "operations",
  settings: "settings",
  notifications: "operations",
  team: "settings",
  support: "operations",
  reviews: "projects",
  calendar: "operations",
  analytics: "dashboard",
  payments: "invoices",
  brand: "settings",
  contracts: "invoices",
  feedback: "operations",
  exports: "settings",
  resources: "settings",
  referrals: "operations",
  integrations: "settings"
};

export const STAFF_PAGE_TO_NOTIFICATION_TAB: Record<StaffPageId, DashboardNotificationTab> = {
  dashboard: "dashboard",
  notifications: "operations",
  tasks: "operations",
  kanban: "operations",
  clients: "messages",
  autodraft: "messages",
  meetingprep: "messages",
  comms: "messages",
  onboarding: "projects",
  health: "projects",
  response: "projects",
  sentiment: "projects",
  lasttouched: "projects",
  portal: "projects",
  smartsuggestions: "projects",
  sprintplanning: "operations",
  taskdependencies: "operations",
  recurringtasks: "operations",
  focusmode: "operations",
  peerrequests: "operations",
  triggerlog: "operations",
  privatenotes: "operations",
  keyboardshortcuts: "operations",
  estimatesactuals: "operations",
  satisfactionscores: "projects",
  knowledge: "operations",
  decisionlog: "operations",
  handoverchecklist: "operations",
  closeoutreport: "operations",
  staffhandovers: "operations",
  context: "projects",
  signoff: "projects",
  standup: "operations",
  retainer: "projects",
  performance: "operations",
  eodwrap: "operations",
  deliverables: "projects",
  timelog: "operations",
  automations: "operations",
  settings: "settings"
};

export const ADMIN_PAGE_TO_NOTIFICATION_TAB: Record<AdminPageId, DashboardNotificationTab> = {
  dashboard: "dashboard",
  leads: "operations",
  clients: "projects",
  projects: "projects",
  invoices: "invoices",
  revops: "operations",
  profitability: "invoices",
  projectProfitability: "invoices",
  cashflow: "invoices",
  fyCloseout: "invoices",
  expenses: "invoices",
  payroll: "invoices",
  pricing: "invoices",
  vendors: "invoices",
  bizdev: "operations",
  portfolio: "projects",
  resources: "operations",
  gantt: "projects",
  qa: "operations",
  sla: "operations",
  onboarding: "operations",
  offboarding: "operations",
  satisfaction: "operations",
  comms: "messages",
  vault: "settings",
  referrals: "operations",
  interventions: "operations",
  team: "operations",
  platform: "settings",
  brand: "settings",
  owner: "settings",
  market: "operations",
  crisis: "operations",
  performance: "operations",
  legal: "settings",
  intelligence: "operations",
  access: "settings",
  messages: "messages",
  notifications: "operations",
  staff: "operations",
  staffOnboarding: "operations",
  leaveAbsence: "operations",
  recruitment: "operations",
  learningDev: "operations",
  staffSatisfaction: "operations",
  employmentRecords: "operations",
  automation: "operations",
  integrations: "operations",
  analytics: "operations",
  reports: "operations",
  audit: "settings",
  experience: "operations",
  settings: "settings",
  executive: "dashboard",
  revenueForecasting: "dashboard",
  teamPerformanceReport: "dashboard",
  portfolioRiskRegister: "dashboard",
  healthScorecard: "dashboard"
};
