import type { PageId } from "./config";

export const pageTitles: Record<PageId, string> = {
  profile: "Account / Profile",
  dashboard: "My Engagements / Dashboard",
  projects: "My Engagements / Project Overview",
  request: "My Engagements / Project Brief",
  approvals: "My Engagements / Change History",
  meetings: "My Engagements / Time Tracking",
  files: "My Engagements / Files",
  feedback: "My Engagements / Feedback & Collaboration",
  billing: "Finance / Deposit & Payments",
  contracts: "Finance / Legal Agreements",
  messages: "Communication / Messages",
  notifications: "Communication / Communication Log",
  reports: "Communication / Status & Launch",
  automation: "Communication / AI & Automation",
  services: "Communication / Services & Growth",
  support: "Account / Progress & Knowledge",
  onboarding: "Account / Onboarding & Offboarding",
  team: "Account / Team Management",
  retainerUsage: "Finance / Retainer Usage",
  sprintVisibility: "My Engagements / Sprint Progress",
  deliverableStatus: "My Engagements / Deliverables",
  milestoneApprovals: "My Engagements / Milestone Approvals",
  healthScore: "Account / Relationship Health",
  satisfactionSurvey: "Account / Give Feedback",
  knowledgeAccess: "Account / Knowledge Base",
  settings: "Account / Security & Access",
};
