/**
 * Dummy data for pages that receive empty-array props.
 * These fill the browse/list views so no page renders blank.
 */

import type {
  ContractDocument,
  RetainerTracker,
  ReportConfig,
  WebVital,
  UptimeRecord,
  SupportTicket,
  KnowledgeArticle,
  OnboardingSection,
  TeamMember,
  TeamAuditEntry,
  NotificationPreference,
  ConnectedIntegration,
  SessionInfo,
} from "./types";

// ── Contracts ────────────────────────────────────────────────────────────────

export const DUMMY_CONTRACTS: ContractDocument[] = [
  {
    id: "ctr-1",
    title: "Master Services Agreement — Maphari × Acme Corp",
    type: "MSA",
    status: "ACTIVE",
    statusTone: "green",
    partyA: "Maphari Technologies",
    partyB: "Acme Corp",
    startAt: "2025-01-15",
    endAt: "2026-01-14",
    amendments: 1,
    fileId: null,
  },
  {
    id: "ctr-2",
    title: "Non-Disclosure Agreement — Maphari × Acme Corp",
    type: "NDA",
    status: "ACTIVE",
    statusTone: "green",
    partyA: "Maphari Technologies",
    partyB: "Acme Corp",
    startAt: "2025-01-10",
    endAt: "2027-01-09",
    amendments: 0,
    fileId: null,
  },
  {
    id: "ctr-3",
    title: "SOW #001 — Brand Identity Redesign",
    type: "SOW",
    status: "ACTIVE",
    statusTone: "green",
    partyA: "Maphari Technologies",
    partyB: "Acme Corp",
    startAt: "2025-02-01",
    endAt: "2025-06-30",
    amendments: 2,
    fileId: null,
  },
  {
    id: "ctr-4",
    title: "SOW #002 — Mobile App Development",
    type: "SOW",
    status: "PENDING_SIGNATURE",
    statusTone: "amber",
    partyA: "Maphari Technologies",
    partyB: "Acme Corp",
    startAt: null,
    endAt: null,
    amendments: 0,
    fileId: null,
  },
  {
    id: "ctr-5",
    title: "IP Transfer — Logo & Brand Assets",
    type: "IP_TRANSFER",
    status: "PENDING_SIGNATURE",
    statusTone: "amber",
    partyA: "Maphari Technologies",
    partyB: "Acme Corp",
    startAt: null,
    endAt: null,
    amendments: 0,
    fileId: null,
  },
  {
    id: "ctr-6",
    title: "SOW — Legacy Website Maintenance",
    type: "SOW",
    status: "EXPIRED",
    statusTone: "red",
    partyA: "Maphari Technologies",
    partyB: "Acme Corp",
    startAt: "2024-01-01",
    endAt: "2024-12-31",
    amendments: 3,
    fileId: null,
  },
  {
    id: "ctr-7",
    title: "Addendum — Rate Adjustment 2025",
    type: "ADDENDUM",
    status: "ACTIVE",
    statusTone: "green",
    partyA: "Maphari Technologies",
    partyB: "Acme Corp",
    startAt: "2025-03-01",
    endAt: "2026-01-14",
    amendments: 0,
    fileId: null,
  },
];

// ── Retainers ────────────────────────────────────────────────────────────────

export const DUMMY_RETAINERS: RetainerTracker[] = [
  {
    id: "ret-1",
    projectName: "Brand Identity Redesign",
    totalHours: 40,
    consumedHours: 28,
    remainingHours: 12,
    periodLabel: "Feb 2026",
  },
  {
    id: "ret-2",
    projectName: "Mobile App Development",
    totalHours: 80,
    consumedHours: 15,
    remainingHours: 65,
    periodLabel: "Feb 2026",
  },
  {
    id: "ret-3",
    projectName: "Website Maintenance",
    totalHours: 20,
    consumedHours: 18,
    remainingHours: 2,
    periodLabel: "Feb 2026",
  },
];

// ── Reports ──────────────────────────────────────────────────────────────────

export const DUMMY_REPORTS: ReportConfig[] = [
  {
    id: "rpt-1",
    title: "Monthly Status Report — February 2026",
    type: "status",
    period: "Feb 2026",
    generatedAt: "2026-02-28T08:00:00Z",
    downloadUrl: null,
    autoEmail: true,
  },
  {
    id: "rpt-2",
    title: "ROI Analysis — Q1 2026",
    type: "roi",
    period: "Q1 2026",
    generatedAt: "2026-02-15T10:00:00Z",
    downloadUrl: null,
    autoEmail: false,
  },
  {
    id: "rpt-3",
    title: "Performance Report — January 2026",
    type: "performance",
    period: "Jan 2026",
    generatedAt: "2026-02-01T08:00:00Z",
    downloadUrl: null,
    autoEmail: true,
  },
  {
    id: "rpt-4",
    title: "SEO Audit — February 2026",
    type: "seo",
    period: "Feb 2026",
    generatedAt: "2026-02-20T14:00:00Z",
    downloadUrl: null,
    autoEmail: false,
  },
  {
    id: "rpt-5",
    title: "Uptime & Reliability — February 2026",
    type: "uptime",
    period: "Feb 2026",
    generatedAt: "2026-02-28T06:00:00Z",
    downloadUrl: null,
    autoEmail: true,
  },
  {
    id: "rpt-6",
    title: "Financial Summary — Q4 2025",
    type: "finance",
    period: "Q4 2025",
    generatedAt: "2026-01-10T09:00:00Z",
    downloadUrl: null,
    autoEmail: false,
  },
];

export const DUMMY_WEB_VITALS: WebVital[] = [
  { metric: "LCP", value: 1.8, unit: "s", status: "good" },
  { metric: "FID", value: 45, unit: "ms", status: "good" },
  { metric: "CLS", value: 0.08, unit: "", status: "good" },
  { metric: "TTFB", value: 320, unit: "ms", status: "needs-improvement" },
  { metric: "INP", value: 180, unit: "ms", status: "needs-improvement" },
  { metric: "FCP", value: 1.2, unit: "s", status: "good" },
];

export const DUMMY_UPTIME_RECORDS: UptimeRecord[] = [
  { service: "Web Application", uptimePercent: 99.97, lastIncident: "2026-01-15T03:22:00Z", status: "operational" },
  { service: "API Gateway", uptimePercent: 99.99, lastIncident: null, status: "operational" },
  { service: "CDN / Static Assets", uptimePercent: 100, lastIncident: null, status: "operational" },
  { service: "Database Cluster", uptimePercent: 99.95, lastIncident: "2026-02-10T11:45:00Z", status: "operational" },
  { service: "Email Delivery", uptimePercent: 98.5, lastIncident: "2026-02-25T16:00:00Z", status: "degraded" },
];

// ── Support ──────────────────────────────────────────────────────────────────

export const DUMMY_TICKETS: SupportTicket[] = [
  {
    id: "tkt-1",
    subject: "Unable to upload files larger than 10 MB",
    category: "Bug Report",
    priority: "high",
    status: "in_progress",
    statusTone: "accent",
    slaDueAt: "2026-03-01T18:00:00Z",
    slaBreached: false,
    createdAt: "2026-02-26T09:15:00Z",
    updatedAt: "2026-02-27T14:30:00Z",
    satisfactionRating: null,
    messages: [
      { id: "msg-1a", content: "When I try to upload a PDF over 10 MB, the upload fails silently. No error message is shown.", authorRole: "client", createdAt: "2026-02-26T09:15:00Z" },
      { id: "msg-1b", content: "Thanks for reporting this! We've identified the issue — our file service has a 10 MB soft limit that needs to be raised. We're deploying a fix now.", authorRole: "support", createdAt: "2026-02-27T14:30:00Z" },
    ],
  },
  {
    id: "tkt-2",
    subject: "Request for additional user seats",
    category: "Account",
    priority: "medium",
    status: "open",
    statusTone: "amber",
    slaDueAt: "2026-03-03T18:00:00Z",
    slaBreached: false,
    createdAt: "2026-02-27T11:00:00Z",
    updatedAt: "2026-02-27T11:00:00Z",
    satisfactionRating: null,
    messages: [
      { id: "msg-2a", content: "Hi, we need to add 3 more team members to our portal. Can you increase our seat limit?", authorRole: "client", createdAt: "2026-02-27T11:00:00Z" },
    ],
  },
  {
    id: "tkt-3",
    subject: "Invoice #INV-042 discrepancy",
    category: "Billing",
    priority: "high",
    status: "resolved",
    statusTone: "green",
    slaDueAt: "2026-02-20T18:00:00Z",
    slaBreached: false,
    createdAt: "2026-02-18T08:30:00Z",
    updatedAt: "2026-02-19T16:00:00Z",
    satisfactionRating: 5,
    messages: [
      { id: "msg-3a", content: "Invoice #INV-042 shows $12,500 but our agreed rate for this milestone was $10,000. Can you check?", authorRole: "client", createdAt: "2026-02-18T08:30:00Z" },
      { id: "msg-3b", content: "You're right — the extra $2,500 was a line item from a previous change request that should have been on a separate invoice. We've issued a corrected invoice.", authorRole: "support", createdAt: "2026-02-19T10:00:00Z" },
      { id: "msg-3c", content: "Perfect, thanks for the quick fix!", authorRole: "client", createdAt: "2026-02-19T16:00:00Z" },
    ],
  },
  {
    id: "tkt-4",
    subject: "How to export project data?",
    category: "How-To",
    priority: "low",
    status: "closed",
    statusTone: "muted",
    slaDueAt: null,
    slaBreached: false,
    createdAt: "2026-02-10T13:00:00Z",
    updatedAt: "2026-02-11T09:00:00Z",
    satisfactionRating: 4,
    messages: [
      { id: "msg-4a", content: "Is there a way to export all project data as a CSV or PDF?", authorRole: "client", createdAt: "2026-02-10T13:00:00Z" },
      { id: "msg-4b", content: "Yes! Go to Reports → select the report type → click the Download button. You can export as PDF or CSV from there.", authorRole: "support", createdAt: "2026-02-11T09:00:00Z" },
    ],
  },
  {
    id: "tkt-5",
    subject: "Dashboard not loading on Safari",
    category: "Bug Report",
    priority: "urgent",
    status: "resolved",
    statusTone: "green",
    slaDueAt: "2026-02-22T12:00:00Z",
    slaBreached: true,
    createdAt: "2026-02-21T17:00:00Z",
    updatedAt: "2026-02-23T10:00:00Z",
    satisfactionRating: 3,
    messages: [
      { id: "msg-5a", content: "The dashboard shows a blank white screen on Safari 17.3. Works fine on Chrome.", authorRole: "client", createdAt: "2026-02-21T17:00:00Z" },
      { id: "msg-5b", content: "We've identified a CSS compatibility issue with Safari. A hotfix has been deployed. Please clear your cache and try again.", authorRole: "support", createdAt: "2026-02-23T10:00:00Z" },
    ],
  },
];

export const DUMMY_ARTICLES: KnowledgeArticle[] = [
  {
    id: "kb-1",
    title: "Getting Started with Your Client Portal",
    category: "Getting Started",
    excerpt: "A quick walkthrough of your portal dashboard, navigation, and key features.",
    content: "Welcome to your Maphari client portal. This guide covers the main areas: Dashboard for an overview, Projects for tracking progress, Messages for team communication, and Billing for invoices and payments.",
    helpful: 42,
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "kb-2",
    title: "Understanding Your Invoice & Payment Status",
    category: "Billing",
    excerpt: "Learn what each invoice status means and how to make payments.",
    content: "Invoice statuses include: Draft (not yet sent), Sent (awaiting payment), Paid (payment received), Overdue (past due date), and Void (cancelled). You can pay invoices directly through the portal.",
    helpful: 38,
    updatedAt: "2026-01-20T14:00:00Z",
  },
  {
    id: "kb-3",
    title: "How to Approve Milestones",
    category: "Projects",
    excerpt: "Step-by-step guide to reviewing and approving project milestones.",
    content: "Navigate to Approvals from the sidebar. You'll see pending items that need your review. Click on a milestone to see deliverables, then approve or request changes.",
    helpful: 29,
    updatedAt: "2026-02-10T08:00:00Z",
  },
  {
    id: "kb-4",
    title: "Managing Team Members & Permissions",
    category: "Team",
    excerpt: "How to invite team members, assign roles, and manage access levels.",
    content: "Go to Team to manage your organization's members. You can invite new members by email, assign roles (Admin, Approver, Editor, Viewer), and revoke access when needed.",
    helpful: 22,
    updatedAt: "2026-02-15T11:00:00Z",
  },
  {
    id: "kb-5",
    title: "Using the Feedback & Annotation Tool",
    category: "Feedback",
    excerpt: "Learn how to leave visual feedback on deliverables with pins and annotations.",
    content: "The Feedback page lets you leave contextual feedback on design deliverables. Click anywhere on the preview to place a pin, add your comment, set priority, and submit.",
    helpful: 18,
    updatedAt: "2026-02-18T09:00:00Z",
  },
  {
    id: "kb-6",
    title: "Keyboard Shortcuts Reference",
    category: "Tips & Tricks",
    excerpt: "Speed up your workflow with these keyboard shortcuts.",
    content: "Press ? anywhere to see available shortcuts. Use G→D for Dashboard, G→P for Projects, G→M for Messages, Cmd+K for quick search, and more.",
    helpful: 15,
    updatedAt: "2026-02-20T16:00:00Z",
  },
];

// ── Onboarding ───────────────────────────────────────────────────────────────

export const DUMMY_ONBOARDING_SECTIONS: OnboardingSection[] = [
  {
    id: "sec-1",
    title: "Account Setup",
    items: [
      {
        id: "onb-1",
        label: "Verify your email address",
        description: "Confirm your email to activate all portal features.",
        section: "Account Setup",
        owner: "client",
        required: true,
        completed: true,
        etaAt: null,
        evidence: "Verified on 2026-02-01",
      },
      {
        id: "onb-2",
        label: "Set up two-factor authentication",
        description: "Enable 2FA for enhanced security on your account.",
        section: "Account Setup",
        owner: "client",
        required: true,
        completed: true,
        etaAt: null,
        evidence: "Enabled on 2026-02-02",
      },
      {
        id: "onb-3",
        label: "Complete company profile",
        description: "Add your company name, logo, and billing address.",
        section: "Account Setup",
        owner: "client",
        required: true,
        completed: false,
        etaAt: "2026-03-05T00:00:00Z",
        evidence: null,
      },
    ],
  },
  {
    id: "sec-2",
    title: "Project Kickoff",
    items: [
      {
        id: "onb-4",
        label: "Review project brief",
        description: "Read through the project brief and scope document shared by the team.",
        section: "Project Kickoff",
        owner: "client",
        required: true,
        completed: true,
        etaAt: null,
        evidence: "Reviewed on 2026-02-05",
      },
      {
        id: "onb-5",
        label: "Sign Master Services Agreement",
        description: "Review and e-sign the MSA in the Contracts section.",
        section: "Project Kickoff",
        owner: "client",
        required: true,
        completed: true,
        etaAt: null,
        evidence: "Signed on 2026-02-06",
      },
      {
        id: "onb-6",
        label: "Attend kickoff meeting",
        description: "Join the project kickoff call to meet the team and align on goals.",
        section: "Project Kickoff",
        owner: "client",
        required: true,
        completed: false,
        etaAt: "2026-03-03T14:00:00Z",
        evidence: null,
      },
      {
        id: "onb-7",
        label: "Share brand assets & guidelines",
        description: "Upload your logo, brand colors, fonts, and any style guidelines.",
        section: "Project Kickoff",
        owner: "client",
        required: false,
        completed: false,
        etaAt: "2026-03-07T00:00:00Z",
        evidence: null,
      },
    ],
  },
  {
    id: "sec-3",
    title: "Team & Access",
    items: [
      {
        id: "onb-8",
        label: "Invite team members",
        description: "Add your colleagues who need access to the portal.",
        section: "Team & Access",
        owner: "client",
        required: false,
        completed: true,
        etaAt: null,
        evidence: "2 members invited",
      },
      {
        id: "onb-9",
        label: "Set notification preferences",
        description: "Configure how you'd like to receive updates (email, in-app, push).",
        section: "Team & Access",
        owner: "client",
        required: false,
        completed: false,
        etaAt: null,
        evidence: null,
      },
    ],
  },
  {
    id: "sec-4",
    title: "Maphari Setup",
    items: [
      {
        id: "onb-10",
        label: "Environment provisioning",
        description: "We'll set up staging and production environments for your project.",
        section: "Maphari Setup",
        owner: "maphari",
        required: true,
        completed: true,
        etaAt: null,
        evidence: "Completed 2026-02-08",
      },
      {
        id: "onb-11",
        label: "Configure CI/CD pipeline",
        description: "Automated deployment pipeline setup for your project.",
        section: "Maphari Setup",
        owner: "maphari",
        required: true,
        completed: true,
        etaAt: null,
        evidence: "Completed 2026-02-10",
      },
      {
        id: "onb-12",
        label: "Set up monitoring & alerts",
        description: "Configure uptime monitoring, error tracking, and performance alerts.",
        section: "Maphari Setup",
        owner: "maphari",
        required: true,
        completed: false,
        etaAt: "2026-03-01T00:00:00Z",
        evidence: null,
      },
    ],
  },
];

/** 8 of 12 items completed → 67% */
export const DUMMY_ONBOARDING_PROGRESS = 67;

// ── Team ─────────────────────────────────────────────────────────────────────

export const DUMMY_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "mem-1",
    name: "Sarah Chen",
    email: "sarah.chen@acmecorp.com",
    role: "admin",
    status: "active",
    twoFactorEnabled: true,
    lastActiveAt: "2026-02-28T09:30:00Z",
    joinedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "mem-2",
    name: "James Wilson",
    email: "james.wilson@acmecorp.com",
    role: "approver",
    status: "active",
    twoFactorEnabled: true,
    lastActiveAt: "2026-02-27T16:45:00Z",
    joinedAt: "2025-02-01T14:00:00Z",
  },
  {
    id: "mem-3",
    name: "Maria Garcia",
    email: "maria.garcia@acmecorp.com",
    role: "editor",
    status: "active",
    twoFactorEnabled: false,
    lastActiveAt: "2026-02-28T08:15:00Z",
    joinedAt: "2025-03-10T09:00:00Z",
  },
  {
    id: "mem-4",
    name: "David Kim",
    email: "david.kim@acmecorp.com",
    role: "viewer",
    status: "active",
    twoFactorEnabled: false,
    lastActiveAt: "2026-02-25T11:00:00Z",
    joinedAt: "2025-06-20T10:00:00Z",
  },
  {
    id: "mem-5",
    name: "Emily Thompson",
    email: "emily.t@acmecorp.com",
    role: "editor",
    status: "invited",
    twoFactorEnabled: false,
    lastActiveAt: null,
    joinedAt: "2026-02-26T15:00:00Z",
  },
  {
    id: "mem-6",
    name: "Robert Patel",
    email: "robert.patel@acmecorp.com",
    role: "viewer",
    status: "suspended",
    twoFactorEnabled: true,
    lastActiveAt: "2026-01-10T09:00:00Z",
    joinedAt: "2025-04-05T11:00:00Z",
  },
];

export const DUMMY_TEAM_AUDIT: TeamAuditEntry[] = [
  { id: "aud-1", action: "Member invited", actorName: "Sarah Chen", detail: "Invited emily.t@acmecorp.com as Editor", createdAt: "2026-02-26T15:00:00Z" },
  { id: "aud-2", action: "Role changed", actorName: "Sarah Chen", detail: "Changed James Wilson from Editor to Approver", createdAt: "2026-02-24T10:30:00Z" },
  { id: "aud-3", action: "Member suspended", actorName: "Sarah Chen", detail: "Suspended Robert Patel — account inactive for 45 days", createdAt: "2026-02-20T14:00:00Z" },
  { id: "aud-4", action: "2FA enabled", actorName: "James Wilson", detail: "Enabled two-factor authentication", createdAt: "2026-02-18T09:15:00Z" },
  { id: "aud-5", action: "Login", actorName: "Maria Garcia", detail: "Logged in from 192.168.1.42 (Chrome / macOS)", createdAt: "2026-02-28T08:15:00Z" },
  { id: "aud-6", action: "Password changed", actorName: "David Kim", detail: "Password updated successfully", createdAt: "2026-02-15T16:00:00Z" },
  { id: "aud-7", action: "Approval granted", actorName: "James Wilson", detail: "Approved Milestone 3 — Homepage Design", createdAt: "2026-02-22T11:00:00Z" },
  { id: "aud-8", action: "File uploaded", actorName: "Maria Garcia", detail: "Uploaded brand-guidelines-v2.pdf (4.2 MB)", createdAt: "2026-02-21T13:30:00Z" },
];

// ── Settings ─────────────────────────────────────────────────────────────────

export const DUMMY_NOTIFICATION_PREFS: NotificationPreference[] = [
  { category: "Project Updates", inApp: true, email: true, push: true },
  { category: "Invoice & Payments", inApp: true, email: true, push: false },
  { category: "Messages", inApp: true, email: true, push: true },
  { category: "Milestone Approvals", inApp: true, email: true, push: true },
  { category: "File Uploads", inApp: true, email: false, push: false },
  { category: "Team Changes", inApp: true, email: true, push: false },
  { category: "Support Tickets", inApp: true, email: true, push: false },
  { category: "Weekly Digest", inApp: false, email: true, push: false },
];

export const DUMMY_INTEGRATIONS: ConnectedIntegration[] = [
  { id: "int-1", name: "Slack", status: "connected", connectedAt: "2025-03-15T10:00:00Z" },
  { id: "int-2", name: "Google Drive", status: "connected", connectedAt: "2025-02-20T14:00:00Z" },
  { id: "int-3", name: "Jira", status: "disconnected", connectedAt: null },
  { id: "int-4", name: "Figma", status: "connected", connectedAt: "2025-06-10T09:00:00Z" },
  { id: "int-5", name: "GitHub", status: "disconnected", connectedAt: null },
  { id: "int-6", name: "Notion", status: "connected", connectedAt: "2025-08-01T16:00:00Z" },
];

export const DUMMY_SESSIONS: SessionInfo[] = [
  { id: "ses-1", device: "Chrome 122 · macOS", location: "San Francisco, CA", ip: "98.42.156.78", lastActiveAt: "2026-02-28T09:30:00Z", current: true },
  { id: "ses-2", device: "Safari 17.3 · iOS", location: "San Francisco, CA", ip: "98.42.156.78", lastActiveAt: "2026-02-27T22:15:00Z", current: false },
  { id: "ses-3", device: "Firefox 124 · Windows", location: "New York, NY", ip: "72.88.200.14", lastActiveAt: "2026-02-25T14:00:00Z", current: false },
];
