import type { PageId } from "./types";

export const pageTitles: Record<PageId, [string, string]> = {
  dashboard: ["Workspace", "Dashboard"],
  notifications: ["Workspace", "Notifications"],
  tasks: ["Assignments", "My Tasks"],
  kanban: ["Sprint 4", "Kanban Board"],
  clients: ["Communication", "Client Threads"],
  autodraft: ["Communication", "Auto-draft Updates"],
  meetingprep: ["Communication", "Meeting Prep"],
  comms: ["Client Intelligence", "Communication History"],
  onboarding: ["Client Management", "Client Onboarding"],
  health: ["Client Intelligence", "Health Score"],
  response: ["Client Intelligence", "Response Time"],
  sentiment: ["Client Intelligence", "Sentiment Flags"],
  lasttouched: ["Client Intelligence", "Last Touched"],
  portal: ["Client Intelligence", "Portal Activity"],
  smartsuggestions: ["Client Intelligence", "Smart Suggestions"],
  sprintplanning: ["Planning", "Sprint Planning"],
  taskdependencies: ["Planning", "Task Dependencies"],
  recurringtasks: ["Planning", "Recurring Tasks"],
  focusmode: ["Focus", "Focus Mode"],
  peerrequests: ["Collaboration", "Peer Requests"],
  triggerlog: ["Automations", "Trigger Log"],
  privatenotes: ["Knowledge", "Private Notes"],
  keyboardshortcuts: ["Help", "Keyboard Shortcuts"],
  estimatesactuals: ["Performance", "Estimates vs Actuals"],
  satisfactionscores: ["Client Intelligence", "Client Health"],
  knowledge: ["Operations", "Knowledge Base"],
  decisionlog: ["Knowledge", "Decision Log"],
  handoverchecklist: ["Workflow", "Handover Checklist"],
  closeoutreport: ["Workflow", "Close-out Report"],
  staffhandovers: ["Workflow", "Staff Handovers"],
  context: ["Client Intelligence", "Project Context"],
  signoff: ["Project Management", "Milestone Sign-off"],
  standup: ["Daily Rhythm", "Daily Standup"],
  retainer: ["Client Finance", "Retainer Burn"],
  performance: ["Personal Growth", "My Performance"],
  eodwrap: ["Daily Rhythm", "End-of-day Wrap"],
  deliverables: ["Output", "Deliverables"],
  timelog: ["Tracking", "Time Log"],
  automations: ["Operations", "Automations"],
  settings: ["Account", "Settings"],
  invoiceviewer: ["Client Finance", "Invoice Viewer"],
  projectbudget: ["Client Finance", "Project Budget"],
  clientbudget: ["Client Finance", "Client Budget"],
  expensesubmit: ["Client Finance", "Expense Submission"],
  paystub: ["Personal Finance", "Pay Stubs"],
  ratecard: ["Client Finance", "Rate Card"],
  vendordirectory: ["Client Finance", "Vendor Directory"],
  myportfolio: ["Project Management", "My Portfolio"],
  mycapacity: ["Project Management", "My Capacity"],
  mytimeline: ["Project Management", "My Timeline"],
  qachecklist: ["Quality", "QA Checklist"],
  approvalqueue: ["Workflow", "Approval Queue"],
  clienthealthsummary: ["Client Intelligence", "Health Summary"],
  feedbackinbox: ["Client Intelligence", "Feedback Inbox"],
  myonboarding: ["HR", "My Onboarding"],
  myleave: ["HR", "My Leave"],
  mylearning: ["HR", "My Learning"],
  myenps: ["HR", "My Feedback (eNPS)"],
  myemployment: ["HR", "My Employment"],
  brandkit: ["Knowledge", "Brand Kit"],
  contractviewer: ["Knowledge", "Contract Viewer"],
  servicecatalog: ["Knowledge", "Service Catalog"],
  projectdocuments: ["Knowledge", "Project Documents"],
  requestviewer: ["Client Lifecycle", "Request Viewer"],
  clientjourney: ["Client Lifecycle", "Client Journey"],
  offboardingtasks: ["Client Lifecycle", "Offboarding Tasks"],
  interventionactions: ["Client Lifecycle", "Intervention Actions"],
  clientteam: ["Client Lifecycle", "Client Team"],
  deliverystatus: ["Client Lifecycle", "Delivery Status"],
  myteam: ["Governance", "My Team"],
  myrisks: ["Governance", "My Risks"],
  systemstatus: ["Governance", "System Status"],
  incidentalerts: ["Governance", "Incident Alerts"],
  myanalytics: ["Analytics", "My Analytics"],
  myreports: ["Analytics", "My Reports"],
  teamperformance: ["Analytics", "Team Performance"],
  myintegrations: ["Settings", "My Integrations"],
  changeRequests: ["Client Lifecycle", "Change Requests"],
  slaTracker: ["Client Lifecycle", "SLA Tracker"],
  appointments: ["Client Work", "Appointments"]
};
