import type { PageId } from "./types";

export const pageTitles: Record<PageId, [string, string]> = {
  dashboard: ["Workspace", "Dashboard"],
  notifications: ["Workspace", "Notifications"],
  tasks: ["Assignments", "My Tasks"],
  kanban: ["Sprint 4", "Kanban Board"],
  clients: ["Communication", "Client Threads"],
  autodraft: ["Communication", "Auto-draft Updates"],
  meetingprep: ["Communication", "Meeting Prep"],
  comms: ["Client Intelligence", "Communication History"],
  onboarding: ["Client Management", "Client Onboarding"],
  health: ["Client Intelligence", "Health Score"],
  response: ["Client Intelligence", "Response Time"],
  sentiment: ["Client Intelligence", "Sentiment Flags"],
  lasttouched: ["Client Intelligence", "Last Touched"],
  portal: ["Client Intelligence", "Portal Activity"],
  smartsuggestions: ["Client Intelligence", "Smart Suggestions"],
  sprintplanning: ["Planning", "Sprint Planning"],
  taskdependencies: ["Planning", "Task Dependencies"],
  recurringtasks: ["Planning", "Recurring Tasks"],
  focusmode: ["Focus", "Focus Mode"],
  peerrequests: ["Collaboration", "Peer Requests"],
  triggerlog: ["Automations", "Trigger Log"],
  privatenotes: ["Knowledge", "Private Notes"],
  keyboardshortcuts: ["Help", "Keyboard Shortcuts"],
  estimatesactuals: ["Performance", "Estimates vs Actuals"],
  satisfactionscores: ["Client Intelligence", "Satisfaction Scores"],
  knowledge: ["Operations", "Knowledge Base"],
  decisionlog: ["Knowledge", "Decision Log"],
  handoverchecklist: ["Workflow", "Handover Checklist"],
  closeoutreport: ["Workflow", "Close-out Report"],
  staffhandovers: ["Workflow", "Staff Handovers"],
  context: ["Client Intelligence", "Project Context"],
  signoff: ["Project Management", "Milestone Sign-off"],
  standup: ["Daily Rhythm", "Daily Standup"],
  retainer: ["Client Finance", "Retainer Burn"],
  performance: ["Personal Growth", "My Performance"],
  eodwrap: ["Daily Rhythm", "End-of-day Wrap"],
  deliverables: ["Output", "Deliverables"],
  timelog: ["Tracking", "Time Log"],
  automations: ["Operations", "Automations"],
  settings: ["Account", "Settings"]
};
