/** Admin dashboard page title mappings — [section, title] tuples for breadcrumbs. */
import type { PageId } from "./config";

export const pageTitles: Record<PageId, [string, string]> = {
  executive: ["Operations", "Executive Dashboard"],
  dashboard: ["Operations", "Business Development"],
  leads: ["Operations", "Leads"],
  clients: ["Operations", "Client Management"],
  projects: ["Projects", "Project Operations"],
  invoices: ["Finance", "Billing"],
  revops: ["Finance", "RevOps Dashboard"],
  revenueForecasting: ["Finance", "Revenue Forecasting"],
  profitability: ["Finance", "Profitability per Client"],
  projectProfitability: ["Finance", "Profitability per Project"],
  cashflow: ["Finance", "Cash Flow Calendar"],
  fyCloseout: ["Finance", "Financial Year Closeout"],
  expenses: ["Finance", "Expense Tracker"],
  payroll: ["Finance", "Payroll Ledger"],
  proposals: ["Finance", "Proposal Builder"],
  pricing: ["Finance", "Pricing Control"],
  vendors: ["Finance", "Vendor & Cost Control"],
  portfolio: ["Operations", "Project Portfolio"],
  resources: ["Operations", "Resource Allocation"],
  gantt: ["Operations", "Timeline & Gantt"],
  qa: ["Operations", "Quality Assurance"],
  sla: ["Operations", "SLA Tracker"],
  onboarding: ["Experience", "Client Onboarding"],
  offboarding: ["Experience", "Client Offboarding"],
  satisfaction: ["Experience", "Client Satisfaction"],
  comms: ["Experience", "Communication Audit"],
  vault: ["Experience", "Document Vault"],
  referrals: ["Experience", "Referral Tracking"],
  interventions: ["Experience", "Health Interventions"],
  team: ["Governance", "Team Structure"],
  platform: ["Governance", "Platform & Infrastructure"],
  brand: ["Governance", "Brand Control"],
  owner: ["Governance", "Owner's Workspace"],
  market: ["Governance", "Competitor & Market Intel"],
  crisis: ["Governance", "Crisis Command"],
  performance: ["Governance", "Performance Overview"],
  staffUtilisation: ["Governance", "Staff Utilisation Rate"],
  capacityForecast: ["Governance", "Capacity Planning Forecast"],
  teamPerformanceReport: ["Governance", "Team Performance Report"],
  portfolioRiskRegister: ["Governance", "Portfolio Risk Register"],
  legal: ["Governance", "Legal Control Center"],
  contractRenewal: ["Governance", "Contract Renewal Tracker"],
  intelligence: ["Governance", "Strategic Client Intelligence"],
  healthScorecard: ["Governance", "Client Health Scorecard"],
  access: ["Governance", "Access Control"],
  messages: ["Communication", "Messages"],
  notifications: ["Communication", "Notifications"],
  staff: ["Communication", "Staff Access"],
  staffOnboarding: ["Communication", "Staff Onboarding"],
  leaveAbsence: ["Communication", "Leave & Absence"],
  recruitment: ["Communication", "Recruitment Pipeline"],
  learningDev: ["Communication", "Learning & Development"],
  staffSatisfaction: ["Communication", "Staff Satisfaction"],
  employmentRecords: ["Communication", "Employment Records"],
  automation: ["Automation", "Workflows"],
  integrations: ["Automation", "Integrations"],
  integrationRequests: ["Automation", "Integration Requests"],
  integrationConnections: ["Automation", "Integration Health"],
  integrationProviders: ["Automation", "Provider Management"],
  analytics: ["Governance", "Analytics"],
  reports: ["Governance", "Reports"],
  audit: ["Governance", "Audit Log"],
  experience: ["Experience", "Client Journey"],
  knowledgeBaseAdmin: ["Knowledge", "Knowledge Base Admin"],
  decisionRegistry: ["Knowledge", "Decision Registry"],
  handoverManagement: ["Knowledge", "Handover Management"],
  closeoutReview: ["Knowledge", "Close-out Review"],
  staffTransitionPlanner: ["Knowledge", "Staff Transition Planner"],
  serviceCatalogManager: ["Knowledge", "Service Catalog Manager"],
  requestInbox: ["Lifecycle", "Request Inbox"],
  changeRequestManager: ["Lifecycle", "Change Request Manager"],
  supportQueue: ["Lifecycle", "Support Queue"],
  lifecycleDashboard: ["Lifecycle", "Lifecycle Dashboard"],
  stakeholderDirectory: ["Lifecycle", "Stakeholder Directory"],
  aiActionRecommendations: ["AI/ML", "AI Action Recommendations"],
  updateQueueManager: ["AI/ML", "Update Queue Manager"],
  standupFeed: ["Governance", "Standup Feed"],
  eodDigest: ["Governance", "EOD Digest"],
  peerReviewQueue: ["Governance", "Peer Review Queue"],
  automationAuditTrail: ["Governance", "Automation Audit Trail"],
  projectBriefing: ["Governance", "Project Briefing"],
  activeHealthMonitor: ["Governance", "Active Health Monitor"],
  announcementsManager: ["Communication", "Announcements Manager"],
  loyaltyCredits: ["Finance", "Loyalty & Credits"],
  bookingAppointments: ["Operations", "Booking & Appointments"],
  designReviewAdmin: ["Experience", "Design Review"],
  sprintBoardAdmin: ["Operations", "Sprint Board"],
  contentApproval: ["Communication", "Content Approval"],
  meetingArchive: ["Communication", "Meeting Archive"],
  prospecting: ["Operations", "AI Prospecting"],
  invoiceChasing: ["Finance", "Invoice Chasing"],
  pipelineAnalytics: ["Finance", "Pipeline Analytics"],
  webhookHub: ["Automation", "Webhook & Integration Hub"],
  clvAnalytics: ["Finance", "CLV & Churn Risk Analytics"],
  projectTemplates: ["Operations", "Project Templates"],
  staffScheduling: ["Communication", "Staff Scheduling"],
  communityModeration: ["Community", "Community Moderation"],
  communityFeatureRequests: ["Community", "Community Feature Requests"],
  proposedActions: ["Governance", "Pending Approvals"],
  settings: ["Account", "Settings"]
};
